
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QTableWidget, QInputDialog, QLineEdit
import os
import shutil
class Ui_MainWindow(object):
    def __init__(self):
        self.file_name = ""
        self.icon_folder = QtGui.QIcon()
        self.icon_folder.addPixmap(QtGui.QPixmap("folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_exe = QtGui.QIcon()
        self.icon_exe.addPixmap(QtGui.QPixmap("exe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_pdf = QtGui.QIcon()
        self.icon_pdf.addPixmap(QtGui.QPixmap("pdf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_txt = QtGui.QIcon()
        self.icon_txt.addPixmap(QtGui.QPixmap("txt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_msi = QtGui.QIcon()
        self.icon_msi.addPixmap(QtGui.QPixmap("msi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_image = QtGui.QIcon()
        self.icon_image.addPixmap(QtGui.QPixmap("picture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_settings = QtGui.QIcon()
        self.icon_settings.addPixmap(QtGui.QPixmap("settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_rar = QtGui.QIcon()
        self.icon_rar.addPixmap(QtGui.QPixmap("rar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_video = QtGui.QIcon()
        self.icon_video.addPixmap(QtGui.QPixmap("video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_unknown = QtGui.QIcon()
        self.icon_unknown.addPixmap(QtGui.QPixmap('unknown.jpg'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_music = QtGui.QIcon()
        self.icon_music.addPixmap(QtGui.QPixmap('music.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_desktop = QtGui.QIcon()
        self.icon_desktop.addPixmap(QtGui.QPixmap('desktop.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_download = QtGui.QIcon()
        self.icon_download.addPixmap(QtGui.QPixmap('download.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_pictures = QtGui.QIcon()
        self.icon_pictures.addPixmap(QtGui.QPixmap('pictures.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_musics = QtGui.QIcon()
        self.icon_musics.addPixmap(QtGui.QPixmap('musics.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_videos = QtGui.QIcon()
        self.icon_videos.addPixmap(QtGui.QPixmap('videos.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_documents = QtGui.QIcon()
        self.icon_documents.addPixmap(QtGui.QPixmap('documents.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_drives = QtGui.QIcon()
        self.icon_drives.addPixmap(QtGui.QPixmap('drives.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_window_icon = QtGui.QIcon()
        self.main_window_icon.addPixmap(QtGui.QPixmap('main_icon.jpg'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_back = QtGui.QIcon()
        self.icon_back.addPixmap(QtGui.QPixmap('back.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_go = QtGui.QIcon()
        self.icon_go.addPixmap(QtGui.QPixmap('go.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_copy = QtGui.QIcon()
        self.icon_copy.addPixmap(QtGui.QPixmap('copy.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_cut = QtGui.QIcon()
        self.icon_cut.addPixmap(QtGui.QPixmap('cut.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_new_folder = QtGui.QIcon()
        self.icon_new_folder.addPixmap(QtGui.QPixmap('new_folder.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_rename = QtGui.QIcon()
        self.icon_rename.addPixmap(QtGui.QPixmap('rename.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon_delete = QtGui.QIcon()
        self.icon_delete.addPixmap(QtGui.QPixmap('delete.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drive_list =[ chr(x) + ":" for x in range(65,90) if os.path.exists(chr(x) + ":") ]
        self.Quick_access = ""
        self.logo_icon = QtGui.QIcon()
        self.logo_icon.addPixmap(QtGui.QPixmap('logo.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    def setupUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setWindowIcon(self.main_window_icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GoButton = QtWidgets.QPushButton(self.centralwidget)
        self.GoButton.setGeometry(QtCore.QRect(1130, 88, 31, 31))
        self.GoButton.setObjectName("pushButton")
        self.GoButton.setFlat(True)
        self.GoButton.setIcon(self.icon_go)
        self.GoButton.setIconSize(QtCore.QSize(30,30))
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(250, 120, 950, 655))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setColumnWidth(0,350)
        self.tableWidget.setColumnWidth(1, 300)
        self.tableWidget.setColumnWidth(2, 300)
        self.tableWidget.setRowCount(len(self.drive_list))
        y = 0
        x = 0
        for i in range(len(self.drive_list)):
            item = QtWidgets.QTableWidgetItem()
            item.setText(self.drive_list[i])
            item.setIcon(self.icon_drives)
            self.tableWidget.setItem(y, 0, item)
            y+=1
        for i in range(len(self.drive_list)):
            item = QtWidgets.QTableWidgetItem()
            item.setText("Drive")
            self.tableWidget.setItem(x, 1, item)
            x+=1
        self.logo = QtWidgets.QPushButton(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(530, 11, 500, 81))
        self.logo.setIconSize(QtCore.QSize(80, 80))
        self.logo.setFlat(True)
        self.logo.setIcon(self.logo_icon)
        self.logo.setIconSize(QtCore.QSize(500, 81))
        self.logo.setObjectName("logo")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget2.setGeometry(QtCore.QRect(10, 120, 230, 655))
        self.tableWidget2.setObjectName("tableWidget2")
        self.tableWidget2.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(0,item)
        self.tableWidget2.setColumnWidth(0,230)
        self.tableWidget2.setRowCount(len(self.drive_list)+6)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Desktop")
        item.setIcon(self.icon_desktop)
        self.tableWidget2.setItem(0,0,item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Downloads")
        item.setIcon(self.icon_download)
        self.tableWidget2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Pictures")
        item.setIcon(self.icon_pictures)
        self.tableWidget2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Musics")
        item.setIcon(self.icon_musics)
        self.tableWidget2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Videos")
        item.setIcon(self.icon_videos)
        self.tableWidget2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Documents")
        item.setIcon(self.icon_documents)
        self.tableWidget2.setItem(5, 0, item)
        x = 1
        for drive in self.drive_list:
            item = QtWidgets.QTableWidgetItem()
            item.setText("Drive" + " "+str(drive))
            item.setIcon(self.icon_drives)
            self.tableWidget2.setItem(5+x, 0, item)
            x+=1
        self.tableWidget2.verticalHeader().setVisible(False)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(520, 95, 600, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(485, 88, 31, 31))
        self.back_button.setObjectName("Back")
        self.back_button.setIcon(self.icon_back)
        self.back_button.setIconSize(QtCore.QSize(30,30))
        self.back_button.setFlat(True)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 105, 461, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 20, 461, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 27, 20, 88))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(460, 27, 20, 88))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(365, 27, 20, 88))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(278, 27, 20, 88))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(185, 27, 20, 88))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(91, 27, 20, 88))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 81, 81))
        self.pushButton.setText("")
        self.pushButton.setIcon(self.icon_new_folder)
        self.pushButton.setIconSize(QtCore.QSize(80, 80))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("new_folder")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 30, 81, 81))
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(self.icon_copy)
        self.pushButton_2.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("copy")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 30, 81, 81))
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(self.icon_cut)
        self.pushButton_3.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("cut")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 30, 81, 81))
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(self.icon_delete)
        self.pushButton_4.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("delete")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 30, 81, 81))
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(self.icon_rename)
        self.pushButton_5.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("rename")





        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.actionNew_folder = QtWidgets.QAction(MainWindow)
        self.actionNew_folder.setObjectName("actionNew_folder")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionRename = QtWidgets.QAction(MainWindow)
        self.actionRename.setObjectName("actionRename")
        self.menuEdit.addAction(self.actionNew_folder)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionRename)
        self.menubar.addAction(self.menuEdit.menuAction())
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.GoButton.clicked.connect(self.go_button)
        self.tableWidget.doubleClicked.connect(self.row_press)
        self.back_button.clicked.connect(self.Back_button)
        self.tableWidget2.clicked.connect(self.quick_access)